sudo: required
dist: focal
language: generic
install:
  - sudo aptitude hold openssh-client
  - sudo aptitude hold openssh-server
  - sudo aptitude hold openssh-sftp-server
  - sudo --preserve-env=HOME USER=$USER ./apt-init-wsl.sh
script:
  - ./tests/apt-init.sh
